In [145]:
import pandas as pd
import numpy as np
from math import exp

input data:
shape = (2,6)

Layer 1

$L1 = h1(input·W1+b1)$

Layer 2

$L2 = h2(L1·W2+b2)$

Output layer

$output = h3(L2·W3+b3)$

activation function
sigmoid function:
h(x)=1/(1+exp(-x))

In [88]:
# sigmoid function
def sigmoid(x):
    return 1/float(1+exp(-x))

In [89]:
# activation
def h(input_array):
    shape = input_array.shape
    return np.array([sigmoid(item) for row in input_array for item in row]).reshape(shape[0],shape[1])

In [62]:
# L1：3个神经元
# L2：6个神经元
# L3：2个神经元
input_data = np.array([[1,2,3,4,5,6],[1,3,5,7,9,11]]) # shape = (2,6) (样本数目，输入数据维数)
W1 = np.array([
        [2,2,2],
        [2,2,2],
        [2,2,2],
        [2,2,2],
        [2,2,2],
        [2,2,2]
    ]) # shape = (输入数据维数,L1神经元数目),
b1 = np.array([[3,3,3]]) # shape = （1，L1神经元数目）
W2 = np.array([
            [1,2,3,3,2,1], 
            [1,2,3,3,2,1],
            [1,2,3,3,2,1]
    ]) # shape = (上一层神经元数目，L2神经元数目) 
b2 = np.array([[7,6,5,4,3,2]]) # shape = （1，L2神经元数目）
W3 =  np.array([ 
            [1,2],
            [3,3],
            [2,3],
            [2,1],
            [1,1],
            [4,5]
    ])# shape = (上一层神经元数目，输出层神经元个数)
b3 = np.array([8,9])# shape = (1,输出层神经元个数)

In [90]:
L1 = h( np.dot(input_data,W1) + b1 )
L1.shape # shape = (样本数目，L1神经元数目)

(2, 3)

In [92]:
L2 = h( np.dot(L1,W2) + b2 )
L2.shape # shape = (样本数目，L2神经元数目)

(2, 6)

In [94]:
L3 = h( np.dot(L2,W3) + b3 )
L3.shape # shape = (样本数目，输出层神经元数目)

(2, 2)

In [95]:
L3

array([[1., 1.],
       [1., 1.]])

In [96]:
def forward(input_data):
    L1 = h( np.dot(input_data,W1) + b1 )
    L2 = h( np.dot(L1,W2) + b2 )
    out = h( np.dot(L2,W3) + b3 )
    return out

In [98]:
forward(input_data)

array([[1., 1.],
       [1., 1.]])

In [112]:
input_data

array([[ 2,  2,  3,  4,  5,  6],
       [ 2,  3,  5,  7,  9, 11]])

In [193]:
inputs = input_data[0,].astype('float64')
inputs

array([3., 2., 3., 4., 5., 6.])

In [194]:
inputs0 = inputs.copy()
inputs0

array([3., 2., 3., 4., 5., 6.])

In [195]:
inputs[0]=inputs[0]+0.01
inputs

array([3.01, 2.  , 3.  , 4.  , 5.  , 6.  ])

In [196]:
inputs0

array([3., 2., 3., 4., 5., 6.])

In [164]:
def mse(pred_out,answer):
    return 0.5*np.sum((pred_out-answer)**2)
    
def cross_entropy(pred_out,answer):
    return -np.sum(answer * np.log(pred_out),axis=1)# 按行求和

def loss_function(pred_out):
    answer = np.array([0.0,1.0])
    N = len(answer)
    return np.sum(cross_entropy(pred_out,answer))/float(N)


In [166]:
loss_function(np.array([[0.1,0.9],[0.2,0.8],[0.5,0.5]]))

0.5108256237659906

In [199]:
def gradient(inputs):
    N = len(inputs)
    gradient = np.array([0]*N)
    delda_x = 0.01
    for i in range(N):
        new_inputs = inputs.copy()
        new_inputs[i] = new_inputs[i]+delda_x
        delda_y = loss_function(forward(inputs))-loss_function(forward(inputs0))
        gradient[i] = delda_y/float(delda_x)
    return gradient
    

In [200]:
gradient(inputs) 

array([0, 0, 0, 0, 0, 0])

In [203]:
def gradient_descent(inputs,params,lr=0.01):
    grads = gradient(inputs)
    inputs = inputs - lr*grads
    return inputs